#!/usr/bin/env python3
"""
sync_contributions.py
Scan greenzorro's public repos for agent-vik mentions and update CONTRIBUTIONS.md
"""

import os
import re
from datetime import datetime
from urllib.request import urlopen, Request
from urllib.error import HTTPError
import json

# Configuration
GREENZORRO_USER = "greenzorro"
AGENT_VIK_PATTERN = r"github\.com/agent-vik"
README_FILENAMES = ["README.md", "readme.md", "README", "readme"]
CONTRIBUTIONS_FILE = "CONTRIBUTIONS.md"

def fetch_json(url):
    """Fetch JSON from URL"""
    req = Request(url, headers={"User-Agent": "agent-vik-sync"})
    with urlopen(req) as response:
        return json.loads(response.read().decode("utf-8"))

def fetch_readme(repo_name):
    """Fetch README content from a repo"""
    for filename in README_FILENAMES:
        try:
            url = f"https://raw.githubusercontent.com/{GREENZORRO_USER}/{repo_name}/main/{filename}"
            req = Request(url, headers={"User-Agent": "agent-vik-sync"})
            with urlopen(req) as response:
                return response.read().decode("utf-8")
        except HTTPError:
            continue
    return None

def get_public_repos():
    """Get all public repos from greenzorro"""
    repos = []
    page = 1
    while True:
        url = f"https://api.github.com/users/{GREENZORRO_USER}/repos?per_page=100&page={page}&sort=created&direction=desc"
        data = fetch_json(url)
        if not data:
            break
        repos.extend(data)
        if len(data) < 100:
            break
        page += 1
    return [r for r in repos if not r.get("private", False) and not r.get("fork", False)]

def find_agent_vik_projects():
    """Find all projects mentioning agent-vik"""
    print(f"[Scan] Fetching {GREENZORRO_USER}'s public repos...")
    repos = get_public_repos()
    print(f"[Scan] Found {len(repos)} public repos")

    projects = []
    for repo in repos:
        repo_name = repo["name"]
        print(f"[Scan] Checking {repo_name}...")

        readme = fetch_readme(repo_name)
        if readme and re.search(AGENT_VIK_PATTERN, readme):
            print(f"[Scan] ✓ Found agent-vik mention in {repo_name}")
            projects.append({
                "name": repo_name,
                "description": repo.get("description") or "No description",
                "url": repo["html_url"],
                "created_at": repo["created_at"][:10],
                "updated_at": repo["updated_at"][:10]
            })

    # Sort by created_at descending (newest first)
    projects.sort(key=lambda x: x["created_at"], reverse=True)
    return projects

def generate_contributions_md(projects):
    """Generate CONTRIBUTIONS.md content"""
    now = datetime.now().strftime("%Y-%m-%d")

    if not projects:
        return f"""# Contributions

> Auto-generated by scanning [greenzorro's repos](https://github.com/greenzorro) for agent-vik mentions.
>
> Last synced: {now}

## Statistics

- Total projects: 0

---

No projects found yet. Projects will appear here when agent-vik is mentioned in greenzorro's README files.
"""

    # Find first contribution (oldest by creation date)
    first_contribution = min(projects, key=lambda x: x["created_at"])["created_at"]

    # Group by year
    by_year = {}
    for p in projects:
        year = p["created_at"][:4]
        if year not in by_year:
            by_year[year] = []
        by_year[year].append(p)

    lines = [
        "# Contributions",
        "",
        f"> Auto-generated by scanning [greenzorro's repos](https://github.com/greenzorro) for agent-vik mentions.",
        ">",
        f"> Last synced: {now}",
        "",
        "## Statistics",
        "",
        f"- Total projects: {len(projects)}",
        f"- First contribution: {first_contribution}",
        "",
        "---"
    ]

    # Sort years descending
    for year in sorted(by_year.keys(), reverse=True):
        lines.append("")
        lines.append(f"## {year}")
        for p in by_year[year]:
            lines.extend([
                "",
                f"### {p['name']}",
                f"- **Role**: Contributor",
                f"- **Repo**: [{GREENZORRO_USER}/{p['name']}]({p['url']})",
                f"- **Description**: {p['description']}",
                f"- **Created**: {p['created_at']}"
            ])

    lines.append("")
    return "\n".join(lines)

def main():
    print("=" * 50)
    print("Agent Vik Contributions Sync")
    print("=" * 50)

    # Find projects
    projects = find_agent_vik_projects()
    print(f"\n[Result] Found {len(projects)} projects with agent-vik mention")

    # Generate content
    content = generate_contributions_md(projects)

    # Write file
    with open(CONTRIBUTIONS_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\n[Done] Updated {CONTRIBUTIONS_FILE}")

    # Print summary
    if projects:
        print("\nProjects:")
        for p in projects:
            print(f"  - {p['name']} (created: {p['created_at']})")

if __name__ == "__main__":
    main()
